[package]
name = "sql-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
convert_case = "0.5.0"
postgres = "0.19.1"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.68"
sqlparser = "0.13.0"